using System.Text.Json;
using System.Text.Json.Nodes;
using CleanArc.Application.Contracts.Adaptive;

namespace CleanArc.Infrastructure.Persistence.Services.Adaptive.Strategies;

internal sealed class TranslationGameStrategy : IGameStrategy
{
    public string GameKey => "translation";
    public string GameTemplateCode => "TRANSLATION";
    public string Category => "RECALL";

    public object GeneratePlayableContent(
        IReadOnlyList<AdaptiveChallengeItemDto> items,
        int difficultyLevel,
        string? configJson)
    {
        string? sourceLanguage = null;
        string? targetLanguage = null;

        if (!string.IsNullOrWhiteSpace(configJson))
        {
            try
            {
                using var doc = JsonDocument.Parse(configJson);
                var root = doc.RootElement;
                if (root.TryGetProperty("sourceLanguage", out var srcProp) && srcProp.ValueKind == JsonValueKind.String)
                {
                    sourceLanguage = srcProp.GetString();
                }
                if (root.TryGetProperty("targetLanguage", out var tgtProp) && tgtProp.ValueKind == JsonValueKind.String)
                {
                    targetLanguage = tgtProp.GetString();
                }
            }
            catch { }
        }

        var mappedItems = items.Select(item =>
        {
            // Parse custom distractors if already generated by AI draft and saved
            JsonNode? distractorsNode = null;
            if (!string.IsNullOrWhiteSpace(item.DistractorsJson))
            {
                distractorsNode = ChallengeGameUtility.TryParseJson(item.DistractorsJson);
            }

            return new
            {
                vocabularyItemId = item.VocabularyItemId,
                word = item.Word,
                normalizedWord = item.NormalizedWord ?? item.Word.Trim().ToLowerInvariant(),
                hint = item.Hint,
                meaningText = item.MeaningText,
                exampleSentence = item.ExampleSentence,
                syllablesJson = ChallengeGameUtility.TryParseJson(item.SyllablesJson) ?? JsonNode.Parse("[]"),
                difficultyLevel = item.DifficultyLevel,
                bmText = item.BmText,
                zhText = item.ZhText,
                enText = item.EnText,
                syllableText = item.SyllableText,
                itemType = item.ItemType,
                displayOrder = item.DisplayOrder,
                syllablePoolJson = JsonNode.Parse("[]"),
                distractorsJson = distractorsNode ?? JsonNode.Parse("[]"),
                correctOrderJson = JsonNode.Parse("[]"),
                spellCatcherSpecJson = JsonNode.Parse("null"),
                language = item.Language
            };
        }).ToList();

        return new
        {
            gameTemplateCode = GameTemplateCode,
            category = Category,
            sourceLanguage = sourceLanguage ?? "ms",
            targetLanguage = targetLanguage ?? "en",
            items = mappedItems
        };
    }
}
