using CleanArc.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CleanArc.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260504090000_AddSpellingTests")]
    public partial class AddSpellingTests : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS spelling_tests (
                  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  classroom_id integer NOT NULL,
                  subject character varying(100) NOT NULL,
                  title character varying(160) NOT NULL,
                  description text NULL,
                  source_module_ids_json jsonb NOT NULL DEFAULT '[]',
                  word_item_ids_json jsonb NOT NULL DEFAULT '[]',
                  due_at timestamp with time zone NOT NULL,
                  status character varying(24) NOT NULL DEFAULT 'ACTIVE',
                  created_by_teacher_id integer NOT NULL,
                  config_json jsonb NOT NULL DEFAULT '{}',
                  created_at timestamp with time zone NOT NULL,
                  updated_at timestamp with time zone NULL,
                  CONSTRAINT "FK_spelling_tests_Classrooms_classroom_id"
                    FOREIGN KEY (classroom_id) REFERENCES "Classrooms" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS student_spelling_test_attempts (
                  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  spelling_test_id integer NOT NULL,
                  student_id integer NOT NULL,
                  status character varying(24) NOT NULL DEFAULT 'NOT_STARTED',
                  score integer NULL,
                  stars integer NULL,
                  started_at timestamp with time zone NULL,
                  completed_at timestamp with time zone NULL,
                  modal_seen_at timestamp with time zone NULL,
                  dismissed_at timestamp with time zone NULL,
                  results_json jsonb NOT NULL DEFAULT '{}',
                  created_at timestamp with time zone NOT NULL,
                  updated_at timestamp with time zone NULL,
                  CONSTRAINT "FK_student_spelling_test_attempts_spelling_tests_spelling_test_id"
                    FOREIGN KEY (spelling_test_id) REFERENCES spelling_tests (id) ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS ix_spelling_tests_classroom_id_status
                  ON spelling_tests (classroom_id, status);
                CREATE INDEX IF NOT EXISTS ix_spelling_tests_classroom_id_title_status
                  ON spelling_tests (classroom_id, title, status);
                CREATE UNIQUE INDEX IF NOT EXISTS ix_student_spelling_test_attempts_spelling_test_id_student_id
                  ON student_spelling_test_attempts (spelling_test_id, student_id);
                CREATE INDEX IF NOT EXISTS ix_student_spelling_test_attempts_student_id_status
                  ON student_spelling_test_attempts (student_id, status);
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
