using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CleanArc.Infrastructure.Persistence.Migrations
{
    public partial class AddAiGovernanceLayer : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS ai_audit_logs (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    use_case character varying(80) NOT NULL,
                    provider character varying(80) NOT NULL,
                    model_name character varying(160) NULL,
                    prompt_version character varying(40) NOT NULL,
                    input_payload_json jsonb NOT NULL DEFAULT '{}',
                    raw_output_json jsonb NULL,
                    parsed_output_json jsonb NULL,
                    validation_status character varying(40) NOT NULL DEFAULT 'PENDING',
                    validation_errors_json jsonb NOT NULL DEFAULT '[]',
                    related_user_id integer NULL,
                    related_classroom_id integer NULL,
                    related_module_id integer NULL,
                    related_challenge_id integer NULL,
                    created_at timestamp with time zone NOT NULL,
                    created_time timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NULL,
                    CONSTRAINT "PK_ai_audit_logs" PRIMARY KEY (id)
                );

                ALTER TABLE "Challenges"
                    ADD COLUMN IF NOT EXISTS ai_generation_status character varying(40) NOT NULL DEFAULT 'NONE';

                ALTER TABLE "Challenges"
                    ADD COLUMN IF NOT EXISTS ai_audit_log_id integer NULL;

                ALTER TABLE "Challenges"
                    ADD COLUMN IF NOT EXISTS ai_use_case character varying(80) NULL;

                CREATE INDEX IF NOT EXISTS "IX_ai_audit_logs_related_challenge_id"
                    ON ai_audit_logs (related_challenge_id);

                CREATE INDEX IF NOT EXISTS "IX_ai_audit_logs_related_classroom_id"
                    ON ai_audit_logs (related_classroom_id);

                CREATE INDEX IF NOT EXISTS "IX_ai_audit_logs_related_module_id"
                    ON ai_audit_logs (related_module_id);

                CREATE INDEX IF NOT EXISTS "IX_ai_audit_logs_related_user_id"
                    ON ai_audit_logs (related_user_id);

                CREATE INDEX IF NOT EXISTS "IX_ai_audit_logs_use_case_created_at"
                    ON ai_audit_logs (use_case, created_at);

                CREATE INDEX IF NOT EXISTS "IX_Challenges_ai_audit_log_id"
                    ON "Challenges" (ai_audit_log_id);

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'FK_ai_audit_logs_Challenges_related_challenge_id'
                    ) THEN
                        ALTER TABLE ai_audit_logs
                            ADD CONSTRAINT "FK_ai_audit_logs_Challenges_related_challenge_id"
                            FOREIGN KEY (related_challenge_id)
                            REFERENCES "Challenges" ("Id")
                            ON DELETE SET NULL;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'FK_Challenges_ai_audit_logs_ai_audit_log_id'
                    ) THEN
                        ALTER TABLE "Challenges"
                            ADD CONSTRAINT "FK_Challenges_ai_audit_logs_ai_audit_log_id"
                            FOREIGN KEY (ai_audit_log_id)
                            REFERENCES ai_audit_logs (id)
                            ON DELETE SET NULL;
                    END IF;
                END $$;
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Challenges_ai_audit_logs_ai_audit_log_id",
                table: "Challenges");

            migrationBuilder.DropTable(
                name: "ai_audit_logs");

            migrationBuilder.DropIndex(
                name: "IX_Challenges_ai_audit_log_id",
                table: "Challenges");

            migrationBuilder.DropColumn(
                name: "ai_generation_status",
                table: "Challenges");

            migrationBuilder.DropColumn(
                name: "ai_audit_log_id",
                table: "Challenges");

            migrationBuilder.DropColumn(
                name: "ai_use_case",
                table: "Challenges");
        }
    }
}
