// <auto-generated />
using System;
using CleanArc.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanArc.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260428120000_AddAiGovernanceLayer")]
    partial class AddAiGovernanceLayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanArc.Domain.Entities.AI.AiAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<string>("InputPayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("input_payload_json");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ModelName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("model_name");

                    b.Property<string>("ParsedOutputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_output_json");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider");

                    b.Property<string>("RawOutputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_output_json");

                    b.Property<int?>("RelatedChallengeId")
                        .HasColumnType("integer")
                        .HasColumnName("related_challenge_id");

                    b.Property<int?>("RelatedClassroomId")
                        .HasColumnType("integer")
                        .HasColumnName("related_classroom_id");

                    b.Property<int?>("RelatedModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("related_module_id");

                    b.Property<int?>("RelatedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("related_user_id");

                    b.Property<string>("UseCase")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("use_case");

                    b.Property<string>("ValidationErrorsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("validation_errors_json");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("validation_status");

                    b.HasKey("Id");

                    b.HasIndex("RelatedChallengeId");

                    b.HasIndex("RelatedClassroomId");

                    b.HasIndex("RelatedModuleId");

                    b.HasIndex("RelatedUserId");

                    b.HasIndex("UseCase", "CreatedAt");

                    b.ToTable("ai_audit_logs", (string)null);
                });

            modelBuilder.Entity("CleanArc.Domain.Entities.Quiz.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AiAuditLogId")
                        .HasColumnType("integer")
                        .HasColumnName("ai_audit_log_id");

                    b.Property<string>("AiGenerationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("NONE")
                        .HasColumnName("ai_generation_status");

                    b.Property<string>("AiUseCase")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("ai_use_case");

                    b.HasKey("Id");

                    b.HasIndex("AiAuditLogId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("CleanArc.Domain.Entities.AI.AiAuditLog", b =>
                {
                    b.HasOne("CleanArc.Domain.Entities.Quiz.Challenge", "RelatedChallenge")
                        .WithMany()
                        .HasForeignKey("RelatedChallengeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RelatedChallenge");
                });

            modelBuilder.Entity("CleanArc.Domain.Entities.Quiz.Challenge", b =>
                {
                    b.HasOne("CleanArc.Domain.Entities.AI.AiAuditLog", "AiAuditLog")
                        .WithMany()
                        .HasForeignKey("AiAuditLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AiAuditLog");
                });
#pragma warning restore 612, 618
        }
    }
}
