using CleanArc.Application.Contracts.Infrastructure;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using QRCoder;

namespace CleanArc.Infrastructure.Persistence.Services;

public class RosterPdfGenerator : IRosterPdfGenerator
{
  public Task<byte[]> GenerateRosterPdfAsync(
      string classroomName,
      IReadOnlyList<StudentCredentialPreview> students,
      CancellationToken cancellationToken)
  {
    QuestPDF.Settings.License = LicenseType.Community;

    var bytes = Document.Create(container =>
    {
      container.Page(page =>
      {
        page.Size(PageSizes.A4);
        page.Margin(1.5f, Unit.Centimetre);
        page.PageColor(Colors.White);

        page.Header().Column(col =>
        {
          col.Item().Text($"{classroomName} - Student Login Badges").Bold().FontSize(20);
          col.Item().Text("Generated by Classroom Setup Wizard").FontSize(10).FontColor(Colors.Grey.Darken1);
        });

        page.Content().PaddingVertical(8).Table(table =>
        {
          table.ColumnsDefinition(columns =>
          {
            columns.RelativeColumn();
            columns.RelativeColumn();
          });

          foreach (var student in students)
          {
            table.Cell().Padding(5).Element(cell =>
            {
              cell.Border(1).BorderColor(Colors.Grey.Lighten1).Padding(10).Column(col =>
              {
                col.Item().Text(student.StudentName).Bold().FontSize(12);
                col.Item().Text($"Login Code: {student.StudentLoginCode}").FontSize(10);
                col.Item().Text($"Visual Password: {student.VisualPassword}").FontSize(10);
                col.Item().PaddingTop(6).Height(90).Image(GenerateQrCode(student.StudentLoginCode)).FitHeight();
              });
            });
          }
        });
      });
    }).GeneratePdf();

    return Task.FromResult(bytes);
  }

  private static byte[] GenerateQrCode(string payload)
  {
    using var qrGenerator = new QRCodeGenerator();
    using var qrCodeData = qrGenerator.CreateQrCode(payload, QRCodeGenerator.ECCLevel.Q);
    using var qrCode = new PngByteQRCode(qrCodeData);
    return qrCode.GetGraphic(10);
  }
}