CREATE TABLE IF NOT EXISTS "GameEnemies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Key" character varying(80) NOT NULL,
    "Name" character varying(120) NOT NULL,
    "ImageRef" character varying(500) NOT NULL,
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedDate" timestamp with time zone NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_GameEnemies_Key" ON "GameEnemies" ("Key");
CREATE INDEX IF NOT EXISTS "IX_GameEnemies_IsActive_DisplayOrder" ON "GameEnemies" ("IsActive", "DisplayOrder");
