ALTER TABLE "Badges" ADD COLUMN IF NOT EXISTS "Code" varchar(100) NOT NULL DEFAULT '';
ALTER TABLE "Badges" ADD COLUMN IF NOT EXISTS "IsActive" boolean NOT NULL DEFAULT true;
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Badges_Code" ON "Badges" ("Code");
