CREATE TABLE IF NOT EXISTS "PushNotificationAttempts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "PushToken" character varying(500) NOT NULL,
    "AlertId" integer NOT NULL,
    "Status" character varying(50) NOT NULL,
    "RetryCount" integer NOT NULL DEFAULT 0,
    "ErrorMessage" text NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedDate" timestamp with time zone NULL
);

CREATE INDEX IF NOT EXISTS "IX_PushNotificationAttempts_UserId" ON "PushNotificationAttempts" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_PushNotificationAttempts_AlertId" ON "PushNotificationAttempts" ("AlertId");
